name = (input("please enter your name:"))
print(name)
surname = (input("please enter your surname:"))
print(surname)
age = (input("please enter your age:"))
print(age)
#თუ მაგალითად ვქმნით ცვლადს და მასში შედის ორი ან მეტი სიტყვა სფეისის ნაცვლად ქვედა ტირეს ვიყენებთ (პითონში)