print("nuki")
print("saba")
print("ani")
print("nia")
print("barbare")
print("nikolozi")
print("anastasia")
print("giorgi")
print("keso")
print("anamaria")
print("lika")
print("gabrieli")
print("luka")
print("mate")
print("ushangi")
print("lela")
print("nino")
print("nana")
print("rusiko")
print("lile")
print("anano")
print("valeri")
print("qeti")
print("solomoni")
print("naniko")
print("eka")
print("maia")
print("darejani")
print("tina")
print("mari")
print("mariami")
print("manana")
print("irakli")
print("rati")
print("tatuli")
print("kato")
print("tamuna")
print("sofo")
print("natia")
print("tazo")
print("dima")
print("iva")
print("ivane")
print("dachi")
print("aleqsandre")
print("andria")
print("noe")
print("sandro")
print("nika")
print("demetre")
print("danieli")
print("toma")
print("lasha")
print("lazare")
print("ilia")
print("beqa")
print("davit")
print("tornike")
print("dato")
print("cotne")
print("zura")
print("erekle")
print("zaza")
print("tato")
print("kote")
print("gurami")
print("guga")
print("temuri")
print("vaxtangi")
print("aleqsi")
print("giga")
print("jemali")
print("kaxa")
print("tedo")
print("shio")
print("tamazi")
print("malxaz")
print("akaki")
print("dimitri")
print("shota")
print("otari")
print("zurabi")
print("zauri")
print("vato")
print("gigi")
print("gocha")
print("badri")
print("vaja")
print("paata")
print("zviadi")
print("soso")
print("elene")
print("cismari")
print("salome")
print("jumberi")
print("sesili")
print("lizi")
print("nene")
print("nita")
print("marta")
print("gvanca")
print("elisabedi")
print("nuca")
print("nica")
print("anita")
print("liza")
print("masho")
print("nini")
print("kesane")
print("tamari")
print("tamila")
print("natali")
print("marita")
print("klara")
print("emili")
print("tatia")
print("ekaterine")
print("tekla")
print("viviana")
print("lana")
print("ioana")
print("teona")
print("eva")
print("alisa")
print("dea")
print("xatia")
print("xatuna")
print("taisa")
print("matilda")
print("elene")
print("lilu")
print("qristine")
print("sofia")
print("kravia")
print("lia")
print("sara")
print("inga")
print("tinatin")
print("anna")
print("tamari")
print("aneta")
print("sesilia")
print("diana")
print("megi")
print("tamta")
print("taso")
print("tako")
print("kesaria")
print("nina")
print("eka")
print("qetevani")
print("natalia")
print("ia")
print("melisa")
print("lali")
print("maka")
print("emilia")
print("magda")
print("nisime")
print("miranda")
print("tea")
print("tatia")
print("nonatata")
print("sofio")
print("rusudan")
print("tekla")
print("mariami")
print("via")
print("omariko")
print("nodari")
print("dali")
print("tristani")
print("kaxa")
print("eliza")
print("nunu")
print("gven")
print("mishel")
print("vefxo")
print("mameda")
print("liana")
print("natela")
print("gela")
print("gia")
print("marine")
print("emzari")
print("cicino")
print("levani")
print("nona")
print("mayvala")
print("mzia")
print("avtandili")
print("eliza")
print("naira")
print("medea")
print("ciala")
print("cicino")
print("klara")
print("ushangi")
print("daviti")
print("aleko")


name1 = "nuki"
print(name1)
name2 = "ani"
print(nam2)
name3 = "nia"
print(name3)
name4 = "mate"
print(name4)
name5 = "luka"
print(name5)
name6 = "nika"
print(name6)
name7 = "dima"
print(name7)
name8 = "anastasia"
print(name8)
name9 = "valeri"
print(name9)
name10 = "manana"
print(name10)
name11 = "gabriali"
print(name11)
name12 = "nino"
print(name12)
name13 = "anano"
print(name13)
name13 = "anamaria"
print(name14)
name14 = "barbare"
print(name15)
name15 = "soso"
print(name16)
name16 = "natali"
print(name17)
name17 = "mariami"
print(name18)
name18 = "lile"
print(name19)
name19 = "elene"
print(name20)
name20 = "saba"
print(name21)
name21 = "solomoni"
print(name22)
name22 = "lia"
print(name23)
name23 = "liana"
print(name24)
name24 = "emzari"
print(name25)
name25 = "paata"
print(name26)
name26 = "mari"
print(name27)
name27 = "dima"
print(name28)
name28 = "iva"
print(name29)
name29 = "tazo"
print(name30)
name30 = "jemali"
print(name31)
name31 = "lela"
print(name32)
name32 = "rati"
print(name33)
name33 = "tatuli" 
print(name34)
name34 = "ilia"
print(name35)
name35 = "dali"
print(name36)
name36 = "nuca"
print(name37)
name37 = "gvanca"
print(name38)
name38 = "aleko"
print(name39)
name39 = "aleqsi"
print(name40)
name40 = "aleqsandre"
print(name41)
name41 = "alika"
print(name42)
name42 = "maia"
print(name43)
name43 = "eka"
print(name44)
name44 = "tea"
print(name45)
name45 = "darejani"
print(name46)
name46 = "tekla"
print(name47)
name47 = "kaxa"
print(name48)
name48 = "zaza"
print(name49)
name49 = "vaxtangi"
print(name50)
name50 = "nana"
print(name50)